name: Deploy Frontend to EC2 via ECR

on:
  push:
    branches: ["main"]

env:
  AWS_REGION: us-east-1
  ECR_REPO: 203783636897.dkr.ecr.us-east-1.amazonaws.com/frontend-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1ï¸âƒ£ Checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # 2ï¸âƒ£ AWS creds (GitHub â†’ ECR)
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # 3ï¸âƒ£ Login to ECR
    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin 203783636897.dkr.ecr.us-east-1.amazonaws.com

    # 4ï¸âƒ£ Build image
    - name: Build Docker image
      run: docker build -t frontend-app .

    # 5ï¸âƒ£ Tag image
    - name: Tag Docker image
      run: docker tag frontend-app:latest $ECR_REPO:latest

    # 6ï¸âƒ£ Push image
    - name: Push Docker image to ECR
      run: docker push $ECR_REPO:latest

    # 7ï¸âƒ£ ðŸš€ Deploy on EC2 (AUTO-INSTALL + RUN)
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 30s
        command_timeout: 10m
        script: |
          set -e
          export ECR_REPO=203783636897.dkr.ecr.us-east-1.amazonaws.com/frontend-app
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_DEFAULT_REGION=us-east-1
          

          echo "ðŸ” Checking Docker..."
          if ! command -v docker &> /dev/null; then
            sudo apt update -y
            sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          echo "ðŸ” Checking AWS CLI..."
          if ! command -v aws &> /dev/null; then
            sudo apt install unzip -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
            unzip awscliv2.zip
            sudo ./aws/install
          fi

          echo "ðŸ”‘ Login to ECR"
          aws ecr get-login-password --region $AWS_DEFAULT_REGION\
          | sudo docker login --username AWS --password-stdin  $ECR_REPO
          echo "â™» Restart container"
          sudo docker stop frontend || true
          sudo docker rm frontend || true

          sudo docker pull $ECR_REPO:latest

          sudo docker run -d \
            --name frontend \
            -p 80:80 \
            $ECR_REPO:latest
